### ISSUE TITLE
非常好的项目,希望尽快完善历史版本显示

### ISSUE THREAD

**Issue by wjy000** [rock-app/fabu.love#111]

**Comment by JackYangFM** [comment]
同感，发布版本后,点击预览,希望下方可以显示历史版本,点击可以切换历史版本！

**Comment by answer-huang** [comment]
@wjy000 @JackYangFM  可以试下这个版本, 加了历史版本的显示, 支持配置:

https://github.com/answer-huang/fabu.love

**Comment by wjy000** [comment]
> @wjy000 @JackYangFM 可以试下这个版本, 加了历史版本的显示, 支持配置:
> 
> https://github.com/answer-huang/fabu.love

非常感谢
