### ISSUE TITLE
ios点击下载安装没有反应

### ISSUE THREAD

**Issue by stardarLeung** [rock-app/fabu.love#113]
发布之后，ios点击下载安装没有反应，用电脑在后台上点下载是正常的，具体是什么问题呢？（用的https，发布的是development版本

**Comment by henlei153** [comment]
我也碰到这个问题了，请问你解决了吗？

**Comment by Suzy-Yy** [comment]
我也碰到了这个问题，请问有解决吗？

**Comment by liericiyan** [comment]
我也碰到了这个问题，请问有解决吗？

**Comment by liericiyan** [comment]
> 我也碰到了这个问题，请问有解决吗？

我的解决了，原因是config.js配置文件里的ip地址我加了端口号，把端口去掉就行了

**Comment by liericiyan** [comment]
> > 我也碰到了这个问题，请问有解决吗？
> 
> 我的解决了，原因是config.js配置文件里的ip地址我加了端口号，把端口去掉就行了

后期测试发现ios12系统版本会提示无法连接到xxx，这个时候需要把你的ssl证书安装到ios端，添加信任，然后就可以了，我是局域网部署，证书生成的时候一定要写你的ip地址

**Comment by answer-huang** [comment]
@stardarLeung @liericiyan @Suzy-Yy @henlei153 可以试下这个仓库, 有问题提 issue:

https://github.com/answer-huang/fabu.love

**Comment by tianmingqq** [comment]
我在config.js配置文件中的IP地址我使用的是（比如https://fabu.love），也没有添加端口号，但是下载iOS包的时候还是没有响应

**Comment by answer-huang** [comment]
iOS 下载需要 https 的链接.

**Comment by tianmingqq** [comment]
> 

我用的就是https的链接

**Comment by tianmingqq** [comment]
> @stardarLeung @liericiyan @Suzy-Yy @henlei153 可以试下这个仓库， 有问题提 issue：
> 
> https://github.com/answer-huang/fabu.love

我也按照您这个去试过，但都卡在了这里：Error: Cannot find module ‘fs/promises‘    我尝试按照网上的方法去升级node版本和降低cnpm的版本，但并没有效果

**Comment by answer-huang** [comment]
> > @stardarLeung @liericiyan @Suzy-Yy @henlei153 可以试下这个仓库， 有问题提 issue：
> > https://github.com/answer-huang/fabu.love
> 
> 我也按照您这个去试过，但都卡在了这里：Error: Cannot find module ‘fs/promises‘ 我尝试按照网上的方法去升级node版本和降低cnpm的版本，但并没有效果

可以私发一个 IPA 包到我邮箱, 我试下.

**Comment by tianmingqq** [comment]
> > > @stardarLeung @liericiyan @Suzy-YY @henlei153 可以试下这个仓库， 有问题提 issue： https://github.com/answer-huang/fabu.love
> > 
> > 
> > 我也按照您这个去试过，但都卡在了这里：Error： 找不到模块 'fs/promises' 我尝试按照网上的方法去升级node版本和降低cnpm的版本，但并没有效果
> 
> 可以给一个 IPA 包我试下.

感觉我们这样沟通效率不太高，可以加下联系方式以便沟通吗？感谢！！！   这是我的QQ：819043880

**Comment by answer-huang** [comment]
麻烦试下最新 master 分支的版本.
