### ISSUE TITLE
在windows下开发没办法跑起来

### ISSUE THREAD

**Issue by wellenzhong** [rock-app/fabu.love#114]
一、先是加密包`bcrypt`没办法安装编译成功，需要执行`npm install --global --production windows-build-tools`安装python后才可以安装；
二、里面的包使用了`natives`,这个包官方已经废弃，并说明让我们用`gaceful-fs`这个包代替。而`graceful-fs`又引用了`natives`
三、需要升级`natives`这个包才行：`npm install --save-dev natives`

**Comment by Yingmansiji** [comment]
我安装了visual studio跑起来了，但是没有办法传apk，不知道怎么做

**Comment by wellenzhong** [comment]
> 我安装了visual studio跑起来了，但是没有办法传apk，不知道怎么做

node后端会报错，我这几天暴改了一个，今天刚内部上线。

**Comment by Yingmansiji** [comment]
安装了docker后可以上传包了，请问你node报了什么错？

**Comment by Yingmansiji** [comment]
> > 我安装了visual studio跑起来了，但是没有办法传apk，不知道怎么做
> 
> node后端会报错，我这几天暴改了一个，今天刚内部上线。

安装了docker后可以上传包了，请问你node报了什么错？

**Comment by wellenzhong** [comment]
> > > 我安装了visual studio跑起来了，但是没有办法传apk，不知道怎么做
> > 
> > 
> > node后端会报错，我这几天暴改了一个，今天刚内部上线。
> 
> 安装了docker后可以上传包了，请问你node报了什么错？

upload.js这个文件时，解析包时读取不到icon,然后就会引用出错。类似于can not read property of null. 
反正后端改了很多。

**Comment by Yingmansiji** [comment]
> > > > 我安装了visual studio跑起来了，但是没有办法传apk，不知道怎么做
> > > 
> > > 
> > > node后端会报错，我这几天暴改了一个，今天刚内部上线。
> > 
> > 
> > 安装了docker后可以上传包了，请问你node报了什么错？
> 
> upload.js这个文件时，解析包时读取不到icon,然后就会引用出错。类似于can not read property of null.
> 反正后端改了很多。

能否加个qq交流？

**Comment by wellenzhong** [comment]
> > > > > 我安装了visual studio跑起来了，但是没有办法传apk，不知道怎么做
> > > > 
> > > > 
> > > > node后端会报错，我这几天暴改了一个，今天刚内部上线。
> > > 
> > > 
> > > 安装了docker后可以上传包了，请问你node报了什么错？
> > 
> > 
> > upload.js这个文件时，解析包时读取不到icon,然后就会引用出错。类似于can not read property of null.
> > 反正后端改了很多。
> 
> 能否加个qq交流？

公司环境不让用qq和微信，倒是可以用钉钉，如果你在用的话：wellenzhong

**Comment by Yingmansiji** [comment]
> wellenzhong

好的

> > > > > > 我安装了visual studio跑起来了，但是没有办法传apk，不知道怎么做
> > > > > 
> > > > > 
> > > > > node后端会报错，我这几天暴改了一个，今天刚内部上线。
> > > > 
> > > > 
> > > > 安装了docker后可以上传包了，请问你node报了什么错？
> > > 
> > > 
> > > upload.js这个文件时，解析包时读取不到icon,然后就会引用出错。类似于can not read property of null.
> > > 反正后端改了很多。
> > 
> > 
> > 能否加个qq交流？
> 
> 公司环境不让用qq和微信，倒是可以用钉钉，如果你在用的话：wellenzhong

好的
