### ISSUE TITLE
iOS 安装提示“无法连接到127.0.0.1”

### ISSUE THREAD

**Issue by liwei721** [rock-app/fabu.love#120]
有碰到类似问题的同学吗？都是怎么解决的呢？

**Comment by imbawales** [comment]
同  救命啊

**Comment by imbawales** [comment]
> 有碰到类似问题的同学吗？都是怎么解决的呢？

我解决了  用nginx配置https，然后改一下fabu.love/server文件夹里面的config.js文件里面的服务器路径和端口号为nginx配置文件里面配置的那个https端口号

**Comment by liwei721** [comment]
> > 有碰到类似问题的同学吗？都是怎么解决的呢？
> 
> 我解决了 用nginx配置https，然后改一下fabu.love/server文件夹里面的config.js文件里面的服务器路径和端口号为nginx配置文件里面配置的那个https端口号

厉害了，我试试

**Comment by liericiyan** [comment]
@imbawales 有没有详细步骤啊，nginx配置https的详细步骤，谢谢大佬
