### ISSUE TITLE
关于ios下载问题

### ISSUE THREAD

**Issue by henlei153** [rock-app/fabu.love#124]
你好，我这里全部部署完成了，但是我扫描ios二维码点击下载安装后，手机端没有任何反应，也没有任何提示信息！请问这是怎么回事？

**Comment by henlei153** [comment]
我的部署环境时这样的

**Comment by henlei153** [comment]
移动端  HTTPS -->   caddy  HTTPS-->  fabu.love后端

**Comment by henlei153** [comment]
由于我没有https证书，所以就使用了caddy自动添加https了
![image](https://user-images.githubusercontent.com/48276442/81359827-d22cae00-910c-11ea-8928-5d3a221e9aa3.png)
这是我的caddy配置

**Comment by henlei153** [comment]
![image](https://user-images.githubusercontent.com/48276442/81360076-79114a00-910d-11ea-9441-3a8e32f6a2c4.png)
这是server/config.js文件里的配置

**Comment by henlei153** [comment]
另外使用微信扫描二维码后什么都不提示，使用qq扫描后提示“fabu.love.com想要安装1个应用程序“点击安装后没有任何提示和反应

**Comment by wowtrxqn** [comment]
> 另外使用微信扫描二维码后什么都不提示，使用qq扫描后提示“fabu.love.com想要安装1个应用程序“点击安装后没有任何提示和反应

我最近也碰到这个问题了，之前是好的，最近几天才有

**Comment by Suzy-Yy** [comment]
我这边部分应用点击安装没有反应

**Comment by henlei153** [comment]
> > 另外使用微信扫描二维码后什么都不提示，使用qq扫描后提示“fabu.love.com想要安装1个应用程序“点击安装后没有任何提示和反应
> 
> 我最近也碰到这个问题了，之前是好的，最近几天才有

咋回事，找到问题了吗？

**Comment by tianmingqq** [comment]
请问解决了吗？好像是突然ios点击下载，然后没响应
