### ISSUE TITLE
Docker镜像发布

### ISSUE THREAD

**Issue by antergone** [rock-app/fabu.love#125]
我认为开发者在docker这一块可以做个优化，把项目的docker镜像打包好推到仓库，这样不用每个人都拉下来编译一遍。

**Comment by answer-huang** [comment]
https://hub.docker.com/repository/docker/answerhuang/fabulove

@antergone 可以试下这个, 最近修复了几个 bug.

**Comment by LDXu** [comment]
@answer-huang  0.0.0.0这个ip打开是空白页咋办？

**Comment by answer-huang** [comment]
> @answer-huang 0.0.0.0这个ip打开是空白页咋办？

加端口了吗 ?

**Comment by gstory0404** [comment]
> > @answer-huang 0.0.0.0这个ip打开是空白页咋办？
> 
> 加端口了吗 ?

使用https://hub.docker.com/repository/docker/answerhuang/fabulove
加了端口 空白页 无法加载出页面，/api/swagger页面可以加载出来，求教怎么处理

**Comment by answer-huang** [comment]
> > > @answer-huang 0.0.0.0这个ip打开是空白页咋办？
> > 
> > 
> > 加端口了吗 ?
> 
> 使用https://hub.docker.com/repository/docker/answerhuang/fabulove 加了端口 空白页 无法加载出页面，/api/swagger页面可以加载出来，求教怎么处理 @answer-huang

看下页面有没有报错. 如果页面没报错,  看下 docker 的日志, 看有没有报错.

**Comment by gstory0404** [comment]
> > > > @answer-huang 0.0.0.0这个ip打开是空白页咋办？
> > > 
> > > 
> > > 加端口了吗 ?
> > 
> > 
> > 使用https://hub.docker.com/repository/docker/answerhuang/fabulove 加了端口 空白页 无法加载出页面，/api/swagger页面可以加载出来，求教怎么处理 @answer-huang
> 
> 看下页面有没有报错. 如果页面没报错, 看下 docker 的日志, 看有没有报错.
docker日志
(node:43) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
数据库连接成功
Process API GET /api/swagger...
Process API GET /api/swagger.json...
Process API GET /api/swagger...
Process API GET /api/swagger.json...
Process API GET /api/swagger.json...
Process API GET /api/swagger...
Process API GET /api/swagger...
Process API GET /api/swagger.json...

页面调试 没有任何报红 @answer-huang

**Comment by gstory0404** [comment]
![20221202163113](https://user-images.githubusercontent.com/17020178/205250317-fd175a74-7a6b-4aec-8d02-e75e96aba38e.jpg) 
@answer-huang

**Comment by gstory0404** [comment]
https://app.distribution.medcloud.cn/assets/index.c375bd9a.js
https://app.distribution.medcloud.cn/assets/vendor.16e51f54.js
https://app.distribution.medcloud.cn/assets/index.d939c185.css
这个几个加载Failed to load resource: net::ERR_CONNECTION_TIMED_OUT 是否是这个引起的 @answer-huang

**Comment by gstory0404** [comment]
![20221202172406](https://user-images.githubusercontent.com/17020178/205260237-d39f9d2b-e4ff-4fcb-bc70-ef02a377e10a.jpg)

这几个脚本加载失败，是否是由这几个导致的 如果修改呢 @answer-huang

**Comment by answer-huang** [comment]
> ![20221202172406](https://user-images.githubusercontent.com/17020178/205260237-d39f9d2b-e4ff-4fcb-bc70-ef02a377e10a.jpg)
> 
> 这几个脚本加载失败，是否是由这几个导致的 如果修改呢 @answer-huang

对的, 这个地方域名应该用配置的. 我有空看下.

**Comment by answer-huang** [comment]
> ![20221202172406](https://user-images.githubusercontent.com/17020178/205260237-d39f9d2b-e4ff-4fcb-bc70-ef02a377e10a.jpg)
> 
> 这几个脚本加载失败，是否是由这几个导致的 如果修改呢 @answer-huang

需要把 ./client/vite.config.js:25 这一行的域名改成自己最终部署的域名, 然后自己编译一个镜像.

**Comment by gstory0404** [comment]
上传app成功，但是无法打开预览页面，查询docker日志 @answer-huang 
```
TypeError: Cannot read property 'appId' of null
    at getAppByShort (/opt/server/controllers/app.js:461:58)
    at /opt/server/swagger/wrapper.js:40:3
    at /opt/server/helper/rest.js:19:21
    at /opt/server/index.js:65:9
    at serve (/opt/server/node_modules/_koa-static@5.0.0@koa-static/index.js:53:9)
    at serve (/opt/server/node_modules/_koa-static@5.0.0@koa-static/index.js:53:9)
    at bodyParser (/opt/server/node_modules/_koa-bodyparser@4.3.0@koa-bodyparser/index.js:95:5)
```

**Comment by answer-huang** [comment]
> 上传app成功，但是无法打开预览页面，查询docker日志 @answer-huang
> 
> ```
> TypeError: Cannot read property 'appId' of null
>     at getAppByShort (/opt/server/controllers/app.js:461:58)
>     at /opt/server/swagger/wrapper.js:40:3
>     at /opt/server/helper/rest.js:19:21
>     at /opt/server/index.js:65:9
>     at serve (/opt/server/node_modules/_koa-static@5.0.0@koa-static/index.js:53:9)
>     at serve (/opt/server/node_modules/_koa-static@5.0.0@koa-static/index.js:53:9)
>     at bodyParser (/opt/server/node_modules/_koa-bodyparser@4.3.0@koa-bodyparser/index.js:95:5)
> ```

是不是 app 没有 icon, 没 icon 的 app 有问题.

**Comment by gstory0404** [comment]
> app 没有 icon, 没 icon 的 app 有

icon确实不显示，在哪里设置，不是上传app自动获取的吗，app的上传下载是OK的 @answer-huang

**Comment by gstory0404** [comment]
> > > app 没有 icon, 没 icon 的 app 有
> > 
> > 
> > icon确实不显示，在哪里设置，不是上传app自动获取的吗，app的上传下载是OK的 @answer-huang
> 
> 这是个 bug, 不支持设置, 给 app 加下 icon 就好了.

手动导入一张图片到icon目录 页面显示正常，但是进入预览页面抓包还是出现这个错误
```
{"success":false,"message":"Cannot read property 'appId' of null"}
```

**Comment by answer-huang** [comment]
> > > > app 没有 icon, 没 icon 的 app 有
> > > 
> > > 
> > > icon确实不显示，在哪里设置，不是上传app自动获取的吗，app的上传下载是OK的 @answer-huang
> > 
> > 
> > 这是个 bug, 不支持设置, 给 app 加下 icon 就好了.
> 
> 手动导入一张图片到icon目录 页面显示正常，但是进入预览页面抓包还是出现这个错误
> 
> ```
> {"success":false,"message":"Cannot read property 'appId' of null"}
> ```

这个要改数据库, 数据库里面有一条记录是解析包的时候存起来的, 你只问了文件, 数据库数据也得改下.

**Comment by gstory0404** [comment]
```
Process API GET /api/apps/63902b63ca26b1001e6475cb/63903a265627a5001afc3336/versions?size=500...
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: invalid signature: 0xff8
    at /opt/server/node_modules/_unzipper@0.10.11@unzipper/lib/parse.js:66:26
    at tryCatcher (/opt/server/node_modules/_bluebird@3.4.7@bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/server/node_modules/_bluebird@3.4.7@bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/opt/server/node_modules/_bluebird@3.4.7@bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/opt/server/node_modules/_bluebird@3.4.7@bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/opt/server/node_modules/_bluebird@3.4.7@bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/opt/server/node_modules/_bluebird@3.4.7@bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/server/node_modules/_bluebird@3.4.7@bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:461:21)
Emitted 'error' event on Parse instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fabu@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabu@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
还有个问题，有时候莫名奇怪的异常，docker容器直接退出，服务挂了 @answer-huang
