### ISSUE TITLE
是否支持自动化打包

### ISSUE THREAD

**Issue by liam-i** [rock-app/fabu.love#130]
您好请问下这个有Fastlane+Jenkins插件吗？

**Comment by zakiso** [comment]
没有 Jenkins插件，不过你可以通过接口 用curl命令直接上传。
fastlane 需要自己配置

**Comment by JackYangFM** [comment]
可以部署Jenkins自动化打包的服务，然后Jenkins可以配置自动上传的脚本，实现自动上传应用
curl -X POST "http://127.0.0.1:9898/api/apps/xxx/upload" -H "accept: application/json" -H "Authorization: Bearer 你的token" -H "content-type: multipart/form-data" -F "file=@/Users/xxx/Desktop/xxx.ipa"

**Comment by Yingmansiji** [comment]
> 可以部署Jenkins自动化打包的服务，然后Jenkins可以配置自动上传的脚本，实现自动上传应用
> curl -X POST "http://127.0.0.1:9898/api/apps/xxx/upload" -H "accept: application/json" -H "Authorization: Bearer 你的token" -H "content-type: multipart/form-data" -F "file=@/Users/xxx/Desktop/xxx.ipa"

返回信息是jwt malformed，这是什么原因呢？

**Comment by carrykx** [comment]
写了个fastlane插件，并发布到rubgems库，直接执行
fastlane add_plugin fabulove
命令就好
https://github.com/carrykx/fastlane-plugin-fabulove
