### ISSUE TITLE
all.css 文件获取不了

### ISSUE THREAD

**Issue by xinhualong** [rock-app/fabu.love#133]
造成进入登录页面卡顿

**Comment by xinhualong** [comment]
有一个all.css需要翻墙才能访问,造成部分功能不能使用,可以把这个问题解决哈不,让我们可能部署在内部

**Comment by carrykx** [comment]
我直接下载的css包，放在本地路径了
https://use.fontawesome.com/releases/v5.14.0/fontawesome-free-5.14.0-web.zip

**Comment by answer-huang** [comment]
@xinhualong 可以试下这个版本.

https://github.com/answer-huang/fabu.love
