### ISSUE TITLE
docker运行只有tcp6而没有tcp问题

### ISSUE THREAD

**Issue by Cabriter** [rock-app/fabu.love#143]

**Comment by Cabriter** [comment]
在docker上运行的发布平台，想通过公网ip端口转发到哪网ip的9898端口，发现无法访问，查看了宿主机上的9898端口只有tcp6而没有tcp。想知道怎么解决。谢谢。🙏

**Comment by ZzMark** [comment]
端口对就成，这就是对linux网络还有docker理解不正确
