### ISSUE TITLE
外网访问以及应用包下载特别慢

### ISSUE THREAD

**Issue by JackYangFM** [rock-app/fabu.love#144]
部署之后，外网访问下载应用包特别慢，想请教一下，有什么解决的思路吗？

**Comment by Leonw2229** [comment]
你把client里的index.html内引用的https://use.fontawesome.com/releases/v5.0.9/css/all.css改成https://www.bootcdn.cn/font-awesome/里相应版本的地址应该就快了，引用包下载慢可能是你服务器贷款不够

**Comment by JackYangFM** [comment]
> 你把client里的index.html内引用的https://use.fontawesome.com/releases/v5.0.9/css/all.css 改成 https://www.bootcdn.cn/font-awesome/ 里相应版本的地址应该就快了，引用包下载慢可能是你服务器带宽不够

嗯嗯 谢谢啦，我也发现是all.css这个文件导致的，这个css国内打不开，需要外网才可以！

**Comment by answer-huang** [comment]
@JackYangFM  可以试下这个版本, 升级了 node 版本, 可以本地运行调试了. 

https://github.com/answer-huang/fabu.love

**Comment by answer-huang** [comment]
可以试下最新的 2.0.0 版本, 代码分支 feat/2.0.0.
