### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by Hemione521** [rock-app/fabu.love#150]
下载完成后，按照前端后端运行的方式直接运行就行么？还需要改什么吗？

**Comment by Hemione521** [comment]
谢谢

**Comment by answer-huang** [comment]
@Hemione521  可以试下这个版本, 之前前端项目本地运行有问题, 这个版本已经更新修复这个问题.

https://github.com/answer-huang/fabu.love

**Comment by answer-huang** [comment]
@Hemione521 麻烦试下最新 master 分支的版本.

**Comment by Hemione521** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
