### ISSUE TITLE
上传安装包卡在100％，

### ISSUE THREAD

**Issue by ai371908858** [rock-app/fabu.love#151]
[您好，非常感谢您这个项目，我是用docker方式部署的，部署完成后，web界面可以正常打开，但是上传文件卡在100％，显示一直在上传，麻烦您指导一下，不指导是不是因为上传目录未指定导致的
![image](https://user-images.githubusercontent.com/33067840/111661534-706fc100-8852-11eb-968f-8470056b8dc0.png)

**Comment by ai371908858** [comment]
![image](https://user-images.githubusercontent.com/33067840/111661766-ab71f480-8852-11eb-831d-e1f50e49a0b5.png)

**Comment by ai371908858** [comment]
![image](https://user-images.githubusercontent.com/33067840/111662060-f12ebd00-8852-11eb-8a2e-583d288f2a4e.png)

**Comment by Cabriter** [comment]
@ai371908858 你好,我也遇到了这个问题,请问有解决方法不.

**Comment by answer-huang** [comment]
@Cabriter @ai371908858 

https://github.com/answer-huang/fabu.love 

可以试下这个版本, 修复了一个 上传100%后卡主的 bug, 如果还有问题可以提 issue.

**Comment by ai371908858** [comment]
好的，非常感谢

answer-huang ***@***.***> 于2021年8月22日周日 下午9:42写道：

**Comment by ai371908858** [comment]
您好，经测试，还是卡在上传100％这个地方

韩彬彬 ***@***.***> 于2021年8月25日周三 下午4:15写道：

**Comment by answer-huang** [comment]
@Cabriter @ai371908858 

可以试下最新的 2.0.0 版本, 代码分支 feat/2.0.0.
