### ISSUE TITLE
麻烦帮忙部署  有偿

### ISSUE THREAD

**Issue by ZhangDiLove** [rock-app/fabu.love#152]
帮忙部署  有偿  有意请回复  谢谢

**Comment by answer-huang** [comment]
https://github.com/answer-huang/fabu.love

@ZhangDiLove  可以试下这个版本, 部署如果有问题可以提 issue.

**Comment by answer-huang** [comment]
可以试下最新的 2.0.0 版本, 代码分支 feat/2.0.0.
