### ISSUE TITLE
上传到100%就卡住了，查看后台代码报错，

### ISSUE THREAD

**Issue by smileLiMingWei** [rock-app/fabu.love#162]
![image](https://user-images.githubusercontent.com/20552477/133592034-89adc963-cf7c-405b-a8b0-4832628befc2.png)
linux环境，感觉好像是aapt-linux这个文件解析上传的包时候出的问题，有大佬指点一下吗

**Comment by smileLiMingWei** [comment]
> ![image](https://user-images.githubusercontent.com/20552477/133592034-89adc963-cf7c-405b-a8b0-4832628befc2.png)
> linux环境，感觉好像是aapt-linux这个文件解析上传的包时候出的问题，有大佬指点一下吗

查看上传指定的存储目录中已经有对应的包了，哪位大佬有没问题的aapt-linux包能给个吗

**Comment by log2c** [comment]
给 aapt-linux +x 权限

**Comment by smileLiMingWei** [comment]
看了node中upload.js的源码，把原来用aapt-linux解析icon的给注掉了，用的app-info-parser这个插件解析出来的图片文件流直接存到数据库了，前端获取文件路径中把对应域名去掉直接在src中放文件流icon显示正常了，不过经过测试部分app解析不出来icon，比如腾讯会议app就没解析出来，不过自己内部使用不会上传很多app只要保证自己app没问题就不影响了。

**Comment by zhangtianming777** [comment]
怎么解决的呢，我现在是苹果的上传会卡住，之前还可以，现在突然就会卡在100%了

**Comment by answer-huang** [comment]
> 怎么解决的呢，我现在是苹果的上传会卡住，之前还可以，现在突然就会卡在100%了

https://github.com/answer-huang/fabu.love

我在最新的 master 分支解决了, 需要自己编译 docker  镜像

**Comment by answer-huang** [comment]
试下最新的 2.0.0 版本, 代码分支 feat/2.0.0, 这个问题已经解决了.
