### ISSUE TITLE
求新版fabu.love仓库的运行环境清单？

### ISSUE THREAD

**Issue by yidongwuxian** [rock-app/fabu.love#172]
git clone https://github.com/answer-huang/fabu.love
本地server服务端cnpm install安装失败，想问下目前正常运行的nodejs版本是多少？

**Comment by wjbd** [comment]
14.20.0就可以

**Comment by answer-huang** [comment]
@yidongwuxian 建议用 docker, 试试最新的 2.0.0 版本.
