### ISSUE TITLE
现在没有迭代更新了吗？是不在维护了吗？

### ISSUE THREAD

**Issue by Avey777** [rock-app/fabu.love#173]
希望可以继续维护

**Comment by tianmingqq** [comment]
你好！我想请教一下，我在config.js配置文件中的IP地址我使用的是（比如[https://fabu.love），也没有添加端口号，但是下载iOS包的时候还是没有响应

**Comment by answer-huang** [comment]
@Avey777 可以试下最新的 2.0.0 版本, 代码分支 feat/2.0.0.

**Comment by answer-huang** [comment]
> 你好！我想请教一下，我在config.js配置文件中的IP地址我使用的是（比如[https://fabu.love），也没有添加端口号，但是下载iOS包的时候还是没有响应

可以试下 docker 版本的. 最新的 2.0.0 版本, 代码分支 feat/2.0.0.
