### ISSUE TITLE
不同系统下上传apk解析iconPath路径错误

### ISSUE THREAD

**Issue by bellchet58** [rock-app/fabu.love#54]
Mac:
![9E91F723595D392DCBDEAD29AD5F31EC](https://user-images.githubusercontent.com/7368054/54112949-3af19b00-4422-11e9-8023-c86588a5273b.jpg)
Ubuntu16.04:
![8192588D4A10EBDDF87D5A7AB9F69497](https://user-images.githubusercontent.com/7368054/54113002-480e8a00-4422-11e9-8e84-e2abd93843ec.png)

用的是同个文件apk，但application-icon-xxx解析到的值不一样。并且在Ubuntu下解析到的application-icon的路径实际并不存在，导致写入icon失败，最后导致了最后上传apk失败。而在Mac上则是正常上传。

所用的apk:
![所用的apk](http://www.kalc.io/assets/images/erweima.png)

**Comment by AlwDnal** [comment]
有在Window上试过么

**Comment by wellenzhong** [comment]
@AlwDnal 我在win上试过，同样的问题

**Comment by answer-huang** [comment]
@bellchet58 @AlwDnal @wellenzhong  试下这个版本, 如果还有问题可以提 issue:

https://github.com/answer-huang/fabu.love
