### ISSUE TITLE
server自行运行报错，primordials is not defined

### ISSUE THREAD

**Issue by raodaqi** [rock-app/fabu.love#75]

**Comment by raodaqi** [comment]
![image](https://user-images.githubusercontent.com/7124789/57488776-a6eb6500-72e6-11e9-9836-66ce52728f00.png)

**Comment by raodaqi** [comment]
测试了下，在node12的版本下会报这个错误

**Comment by answer-huang** [comment]
@raodaqi 升级了 node 版本的支持, 可以试下这个版本:

https://github.com/answer-huang/fabu.love
