### ISSUE TITLE
上传安卓apk包后server端报错

### ISSUE THREAD

**Issue by qq771026828** [rock-app/fabu.love#80]
/data/tools/LoveFabu/server/controllers/upload.js:365
                if (typeof data['application-icon-' + iconSize[i]] !== 'undefined') {
                               ^

TypeError: Cannot read property 'application-icon-640' of undefined
    at apkParser3 (/data/tools/LoveFabu/server/controllers/upload.js:353:28)
    at /data/tools/LoveFabu/server/library/apkparser/apkparser.js:22:14
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:448:20)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at Pipe._handle.close (net.js:606:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fabu@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabu@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-17T06_15_09_864Z-debug.log
[root@appfabu server]#

**Comment by qq771026828** [comment]
请问需要怎么解决？ centos下部署的环境，部署好了 上传APK导致server直接报错

**Comment by qq771026828** [comment]
额   没人解决？

**Comment by chihong2012** [comment]
https://segmentfault.com/a/1190000011710031

glibc 版本过低

按照这链接升级到 2.17 就好了

**Comment by linyicong** [comment]
@qq771026828 这个问题你有解决了吗，

**Comment by qq771026828** [comment]
没有，弃用了&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "linyicong"<notifications@github.com&gt;; 
发送时间: 2019年11月29日(星期五) 下午5:52
收件人: "headingmobile/fabu.love"<fabu.love@noreply.github.com&gt;; 
抄送: "无语"<771026828@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [headingmobile/fabu.love] 上传安卓apk包后server端报错 (#80)




@qq771026828 这个问题你有解决了吗，

**Comment by yolo2h** [comment]
#112
