### ISSUE TITLE
iOS 安装提示“无法连接到127.0.0.1”;

### ISSUE THREAD

**Issue by AgoniNemo** [rock-app/fabu.love#84]
fabu_nginx.conf里的配置
```
server{
  listen 80;
  server_name fabu.love;
  

  root /home/ubuntu/fabulove/server/uploaded;
  index index.html;

  location / {
      try_files $uri $uri/ @router;
      index index.html;
  }

  location @router {
      rewrite ^.*$ /index.html last;
  }

  location /upload/ {
      #该目录为根目录下config文件里配置的文件上传目录
      #或者使用node app config 配置的updateDir
      root /home/ubuntu/fabulove/upload;
      expires  30d;
  }


  location /api/ {
    proxy_pass https://192.168.0.253:9898;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
  client_max_body_size 208M; 
}

server{
  listen 443;
  server_name wiki.fabu.love;
  
  ssl on;  
  ssl_buffer_size 64k;
  ssl_certificate ssl/server.crt;
  ssl_certificate_key ssl/server.key;
  ssl_session_timeout  5m;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_prefer_server_ciphers   on;

  root /home/ubuntu/fabulove/wiki/_book;
  index index.html;
}
```

server/config.js 配置
```
var fs = require("fs")
var path = require("path")


const common = {

    baseUrl: process.env.FABU_BASE_URL || "https://192.168.0.253:9898", //baseUrl应用请求的url地址,比如https://fabu.love
    port: process.env.FABU_PORT || "9898", //server运行的端口
    apiPrefix: 'api',
    fileDir: process.env.FABU_UPLOAD_DIR || path.join(__dirname, ".."), //上传文件的存放目录
    secret: process.env.FABU_SECRET || "secretsecret", //secret
    dbUser: process.env.FABU_DBUSER || undefined, //数据库用户 (没有开启mongodb用户认证的可以不填写)
    dbPass: process.env.FABU_DBPWD || undefined, //数据库密码 (没有开启mongodb用户认证的可以不填写)
    dbName: process.env.FABU_DB_NAME || "fabulove", //数据库名称
    dbHost: process.env.FABU_DB_HOST || "0.0.0.0", //数据库地址
    dbPort: process.env.FABU_DB_PORT || "27017", //数据库端口

    emailService: process.env.FABU_EMAIL_SERVICE || "qq", //邮件相关配置 用于找回密码和邀请团队成员发送邮件
    emailUser: process.env.FABU_EMAIL_USER || "",
    emailPass: process.env.FABU_EMAIL_PASS || "",
    emailPort: process.env.FABU_EMAIL_PORT || "587",

    allowRegister: boolConfig(process.env.FABU_ALLOW_REGISTER || "true"), //是否允许用户注册,为否则后端注册接口不可用

    openLdap: boolConfig(process.env.FABU_ALLOW_LDAP || "false"), //是否开启ldap 默认是false 如果公司没有ldap服务可以不用理会
    ldapServer: process.env.FABU_LDAP_URL || "", //ldap server url
    ldapUserDn: process.env.FABU_LDAP_USERDN || "", //ldap管理员dn 也就是管理员用户名
    ldapBindCredentials: process.env.FABU_LDAP_CREDENTIALS || "", //ldap管理员密码
    ldapBase: process.env.FABU_LDAP_BASE || "", //ldap base
};

function boolConfig(str) {
    if (str == 'true') {
        return true
    } else {
        return false
    }
}

```
本地自签名证书生成用的是[https://ningyu1.github.io/site/post/51-ssl-cert/](https://ningyu1.github.io/site/post/51-ssl-cert/)里的第二种方法
是不是因为域名填的是`192.168.0.253:9898` 

已经尝试过  [#39](https://github.com/HeadingMobile/fabu.love/issues/39)  [#67](https://github.com/HeadingMobile/fabu.love/issues/67)

**Comment by imbawales** [comment]
你好 请问这个解决了吗。。

**Comment by liericiyan** [comment]
解决了吗？

**Comment by JackYangFM** [comment]
有同学解决了吗？iOS遇到了同样的问题 点击安装 提示“无法连接到127.0.0.1”

**Comment by liericiyan** [comment]
> 有同学解决了吗？iOS遇到了同样的问题 点击安装 提示“无法连接到127.0.0.1”，能输出一下具体的配置代码不，谢谢啦！

配置好了https协议之后，还要保证生成的ca证书没问题，部分ios机型需要手动信任此证书

**Comment by JackYangFM** [comment]
> > 有同学解决了吗？iOS遇到了同样的问题 点击安装 提示“无法连接到127.0.0.1”，能输出一下具体的配置代码不，谢谢啦！
> 
> 配置好了https协议之后，还要保证生成的ca证书没问题，部分ios机型需要手动信任此证书

能具体给个配置的代码不

**Comment by JackYangFM** [comment]
> > 有同学解决了吗？iOS遇到了同样的问题 点击安装 提示“无法连接到127.0.0.1”，能输出一下具体的配置代码不，谢谢啦！
> 
> 配置好了https协议之后，还要保证生成的ca证书没问题，部分ios机型需要手动信任此证书

能贴一下相关的配置文件代码不，iOS证书具体怎么操作的啊，谢谢！

**Comment by liericiyan** [comment]
> > > 有同学解决了吗？iOS遇到了同样的问题 点击安装 提示“无法连接到127.0.0.1”，能输出一下具体的配置代码不，谢谢啦！
> > 
> > 
> > 配置好了https协议之后，还要保证生成的ca证书没问题，部分ios机型需要手动信任此证书
> 
> 能贴一下相关的配置文件代码不，iOS证书具体怎么操作的啊，谢谢！

docker run --detach --name wx-nginx -p 443:443 -p 8080:8080 -v D:\mdockertest\html:/usr/share/nginx/html:rw -v D:\mdockertest\nginx/nginx.conf:/etc/nginx/nginx.conf:rw -v D:\mdockertest\nginx/default.conf:/etc/nginx/conf.d/default.conf:rw -v D:\mdockertest\logs:/var/log/nginx/:rw -v D:\mdockertest\ssl:/ssl/:rw -d nginx


证书生成步骤
第一步：openssl genrsa -des3 -out server.key 2048

第二步：openssl req -new -key server.key -out server.csr                       
//windows运行这一步会报错Unable to load config info from /usr/local/ssl/openssl.cnf
解决方案：
set OPENSSL_CONF=C:\Program Files (x86)\Git\ssl\openssl.cnf

------------------------------------------------
//示例
Country Name (2 letter code) [AU]: 国家名称
State or Province Name (full name) [Some-State]: 省
Locality Name (eg, city) []: 城市
Organization Name (eg, company) [Internet Widgits Pty Ltd]: 公司名
Organizational Unit Name (eg, section) []: 
Common Name (e.g. server FQDN or YOUR name) []: 网站域名
Email Address []: 邮箱

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []: 这里要求输入密码
An optional company name []:
-------------------------------------------------

第三步：openssl rsa -in server.key -out server_nopwd.key

第四步：openssl x509 -req -days 365 -in server.csr -signkey server_nopwd.key -out server.crt


苹果系统可能需要信任一下证书，安装地址：https://192.168.20.126/static/server.crt

**Comment by liericiyan** [comment]
> > > 有同学解决了吗？iOS遇到了同样的问题 点击安装 提示“无法连接到127.0.0.1”，能输出一下具体的配置代码不，谢谢啦！
> > 
> > 
> > 配置好了https协议之后，还要保证生成的ca证书没问题，部分ios机型需要手动信任此证书
> 
> 能贴一下相关的配置文件代码不，iOS证书具体怎么操作的啊，谢谢！

default.conf文件：
server {
    listen    8080;       #侦听80端口，如果强制所有的访问都必须是HTTPs的，这行需要注销掉
	listen    443 ssl;
    server_name  localhost;             #域名
	
	# 增加ssl
    #ssl on;        #如果强制HTTPs访问，这行要打开
    ssl_certificate /ssl/server.crt;
    ssl_certificate_key /ssl/server.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

     # 指定密码为openssl支持的格式
     ssl_protocols  SSLv2 SSLv3 TLSv1.2;

     ssl_ciphers  HIGH:!aNULL:!MD5;  # 密码加密方式
     ssl_prefer_server_ciphers  on;   # 依赖SSLv3和TLSv1协议的服务器密码将优先于客户端密码
	#root /usr/share/nginx/html;
	#index index.html;
	
    charset utf-8;
  
	location / {
		proxy_pass http://172.17.0.1:9898; #这里端口修改为后端服务运行的端口
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
  client_max_body_size 508M; #最大上传的ipa/apk文件大小

    #定义错误提示页面
    #error_page  404              /404.html;

    #重定向错误页面到 /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
--------------------
nginx.conf文件：

#运行nginx的用户
user  nginx;
#启动进程设置成和CPU数量相等
worker_processes  1;

#全局错误日志及PID文件的位置
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

#工作模式及连接数上限
events {
        #单个后台work进程最大并发数设置为1024
    worker_connections  1024;
}


http {
        #设定mime类型
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

        #设定日志格式
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

        #设置连接超时的事件
    keepalive_timeout  65;

        #开启GZIP压缩
    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

**Comment by liericiyan** [comment]
> > > 有同学解决了吗？iOS遇到了同样的问题 点击安装 提示“无法连接到127.0.0.1”，能输出一下具体的配置代码不，谢谢啦！
> > 
> > 
> > 配置好了https协议之后，还要保证生成的ca证书没问题，部分ios机型需要手动信任此证书
> 
> 能贴一下相关的配置文件代码不，iOS证书具体怎么操作的啊，谢谢！

有啥问题可以加我微信askOK1234567890详细讨论

**Comment by JackYangFM** [comment]
已解决 服务端部署方法如下：
1. 找到docker下面的docker-compose.yml
environment:
      FABU_DB_HOST: mongo
      # FABU_BASE_URL: https://fabu.apppills.com 正式环境部署请打开注释，并修改为域名为自己的域名
      FABU_UPLOAD_DIR: /fabu/upload

将FABU_BASE_URL注释打开并修改为自己的域名（eg：https://fabu.xxx.com）


2. 找到根目录下fabu_nginx.conf
location /api/ {
    proxy_pass http://127.0.0.1:8383;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
将proxy_pass 修改为 http://127.0.0.1:9898 （端口由8383改为9898即可其他不用改）

备注：证书我没安装，就修改了上面两个文件就可以了，其他文件都没有动！供大家参考
