### ISSUE TITLE
项目运行报错，跑不起来

### ISSUE THREAD

**Issue by Avatarwebwwt** [rock-app/fabu.love#87]
执行 npm run dev 后报错。-.-
![image](https://user-images.githubusercontent.com/32385187/61696527-17434780-ad68-11e9-8473-c729b48aedac.png)

**Comment by answer-huang** [comment]
@Avatarwebwwt 可以试下这个版本, 更新成 vite 打包了:

https://github.com/answer-huang/fabu.love

**Comment by Avatarwebwwt** [comment]
谢谢回复，已经转行不写代码了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月22日(星期天) 晚上9:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [rock-app/fabu.love] 项目运行报错，跑不起来 (#87)





 
@Avatarwebwwt 可以试下这个版本, 更新成 vite 打包了:
 
https://github.com/answer-huang/fabu.love
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
