### ISSUE TITLE
每个项目上传构建版本最大上限

### ISSUE THREAD

**Issue by JiaFangzhou** [rock-app/fabu.love#88]
每个项目上传构建版本最大上限是10个吗？为什么上传了10个之后后面的构建版本就显示不出来了？

**Comment by zakiso** [comment]
没有限制 应该是bug

**Comment by answer-huang** [comment]
> 应该

api 接口默认返回了 10 个, 我 fork 过去改了.

**Comment by answer-huang** [comment]
> 没有限制 应该是bug

api 接口默认返回了 10 个, 我 fork 过去改了.

**Comment by answer-huang** [comment]
麻烦试下最新 master 分支的版本. @JiaFangzhou
