### ISSUE TITLE
npm run dev 出错

### ISSUE THREAD

**Issue by wumuwumu** [rock-app/fabu.love#89]
客户端程序运行npm run dev 程序出错，webpack3与webpack-dev-server3.1.11是不是不兼容。

错误：
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

**Comment by answer-huang** [comment]
@wumuwumu 可以试下这个版本, 已经升级成 vite 打包, 可以本地运行:

https://github.com/answer-huang/fabu.love
