### ISSUE TITLE
docker 启动访问不了，demo也不能使用

### ISSUE THREAD

**Issue by yiweizhi** [rock-app/fabu.love#96]
docker 启动访问不了，demo也不能使用

**Comment by JayceTsien** [comment]
同 demo无法注册 也无法登录
![image](https://user-images.githubusercontent.com/42892849/69058839-65830180-0a4f-11ea-8f09-ee58b5de4060.png)

**Comment by answer-huang** [comment]
docker 重启下，可能就好了，我也遇到这个问题。
