### ISSUE TITLE
ipa 上传卡在100%不动

### ISSUE THREAD

**Issue by jerome-chen** [rock-app/fabu.love#98]
apk 没有问题。

服务端 LOGO 最后显示：

116|apps   | 2019-11-22 12:52 +08:00: icon base64 ---->  null

**Comment by wellenzhong** [comment]
那是因为后端崩了，但没给前端响应。
整个系统需要添加错误捕捉并做出响应。

**Comment by answer-huang** [comment]
@jerome-chen  可以试下这个版本, 修复了这个问题, 是因为 aapt 版本问题, 在解析 ipa 包时报错了:

https://github.com/answer-huang/fabu.love

**Comment by smileLiMingWei** [comment]
> @jerome-chen 可以试下这个版本，修复了这个问题，是因为 aapt 版本问题，在解析 ipa 包时报错了：
> 
> https://github.com/answer-huang/fabu.love

就是下载的你这版本的，aapt的一样解析不了文件

**Comment by answer-huang** [comment]
看一下，是不是你的 ipa 没有 icon。 没有 icon 会这样.

**Comment by lokewei** [comment]
> @jerome-chen 可以试下这个版本, 修复了这个问题, 是因为 aapt 版本问题, 在解析 ipa 包时报错了:
> 
> https://github.com/answer-huang/fabu.love

这个版本赞啊，希望能继续更新

**Comment by answer-huang** [comment]
> 

要看有没有什么诉求了.
